ersion: "2.4"
services:
    mongodb-pio:
        image: mongo:latest
        container_name: "mongodb-pio"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27020:27017
        deploy:
          resources:
            limits:
              memory: 10G
            reservations:
              memory: 2G