version: "2"
services:
  mongo-pio:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27018"
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 10M
        reservations:
          memory: 5M