version: "2.2"
services:
    mongopio:
        image: mongo:latest
        container_name: "mongopio"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/logs
        volumes:
          - ./data/db:/data/db
        ports:
            - 27028:27017
        mem_limit: 8192m
